### ISSUE TITLE
request for publishing to atmosphere/meteor

### ISSUE THREAD

**Issue by mraky** [cytoscape/cytoscape.js-cose-bilkent#11]
Hello,
would you be so kind, and publish it to atmosphere/meteor, please ? cose-bilkent, which is already published to atmosphere, is 
maxkfranz:cytoscape-cose-bilkent
, but it depend on maxkfranz:cytoscape, which is older version

it would be perfect, if cose-bilken is avaiable for already published https://atmospherejs.com/cytoscape/cytoscape

thank you alot.

**Comment by maxkfranz** [comment]
Meteor looks like it finally had support for team publishing, so this may be possible

**Comment by maxkfranz** [comment]
https://github.com/cytoscape/cytoscape.js/issues/1296

**Comment by maxkfranz** [comment]
I spoke too soon.  It looks like their organisation support is lacking.  It would mean that the `cytoscape:cytoscape` package would need to be renamed just to use organisations.  That's ridiculous.

Meteor 1.3 will support npm properly:  https://forums.meteor.com/t/meteor-1-3-here-and-now-its-time-to-think-about-npm/14725

You can also use npm with 1.2: https://github.com/meteorhacks/npm

We may keep the `cytoscape:cytoscape` package for a while, but we'll probably drop the package since npm is superior to meteor's package system.

**Comment by maxkfranz** [comment]
I've removed the old maxkfranz:* packages.  Meteor was broken for a long time, and they couldn't be removed.
