### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by danpaulsmith** [cytoscape/cytoscape.js-cose-bilkent#12]
https://github.com/cytoscape/cytoscape.js-cose-bilkent/blob/master/cytoscape-cose-bilkent.js#L5121

I think it should be "this.cy" instead of "cy".

```var cyNode = this.cy.getElementById(lNode.id).parent()[0];```

It was throwing an error, which I corrected in the source file and now all's ok for me.

**Comment by metincansiper** [comment]
@danpaulsmith 
You are right. It should be 'this.cy' instead of 'cy'. In the application where I am usually testing cose-bilkent there is a global variable 'cy', so I could not find out this error before. I have committed the changes after replacing 'cy' with 'this.cy' as you described. Thanks for informing us.

**Comment by maxkfranz** [comment]
Published as 1.2.2

@metincansiper In general, each bugfix should get a new  patch release once it's closed.
