### ISSUE TITLE
layout doesn t stop

### ISSUE THREAD

**Issue by misu200** [cytoscape/cytoscape.js-cose-bilkent#13]
I have the following fragment of code where I try to stop a running layout:

            var options = {
              name: 'cose-bilkent',
               // Called on `layoutready`
              ready: function () {
                  console.log("LAYOUT READY");
              },
              // Called on `layoutstop`
              stop: function () {
                  console.log("LAYOUT STOP");
              },
                   fit:true,padding:20,randomize:false,nodeRepulsion:40500,idealEdgeLength:70,edgeElasticity:0.45,nestingFactor:0.9,gravity:0.9,numIter:1000,tile:true,us eMultitasking:true,animate:false
            }

            var layout = cy.makeLayout(options);

            layout.run();
            console.log("DONE");

            setTimeout(function() {
                console.log("LAYOUT_FORCED_STOP");
                layout.stop();
            }, 5000);
However it seems the layout doesn't stop after 5 seconds:

DONE
Thread log: start thread
LAYOUT_FORCED_STOP
Classic CoSE layout finished after 1000 iterations
Total execution time: 10597 miliseconds.
LAYOUT READY
LAYOUT STOP

**Comment by maxkfranz** [comment]
@metincansiper Any idea why the layout would have this behaviour?

**Comment by metincansiper** [comment]
@maxkfranz I think that the problem was related to that we changed cose-bilkent to the threaded version, but I did not change "_CoSELayout.prototype.stop" function respectively. Now I have changed it by considering the thread. You can see the latest commit I have linked to this issue.

@misu200 
New output I have obtained is the following one,

DONE 
LAYOUT_FORCED_STOP
LAYOUT READY
LAYOUT STOP
