### ISSUE TITLE
Layout doesn't run if all nodes share the same position

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js-cose-bilkent#14]
Refer to https://github.com/cytoscape/cytoscape.js/issues/1372

**Comment by maxkfranz** [comment]
@metincansiper Any idea why this would be happening?  Thanks!

**Comment by ugurdogrusoz** [comment]
Regular layout starts with random positions; so this can only happen when all nodes are at the same position and incremental layout is enabled. One shouldn't run incremental layout when nodes don't really have any initial positions (all are at the same location). One way to avoid this is to randomly move nodes at least a little bit.
So what exactly is observed when they are at the same location?

**Comment by aindlq** [comment]
I tried to enable `randomized: true`, move nodes out of the same point, apply random layout before cose-bilkent, but it has no effect on "cose-bilkent" layout. 

see http://jsbin.com/yuremezoma/1/edit?html,output , try to collapse and then expand some compound node

**Comment by ugurdogrusoz** [comment]
Interesting. Why do you apply layout on child content upon expand? Why not just break the parent-child relations upon collapse but keep the child nodes around with their locations and restore them upon expand? Here is an example, where we do exactly that: http://cs.bilkent.edu.tr/~ivis/SBGNViz.js_editor/sample-app/

**Comment by maxkfranz** [comment]
Maybe it's because the layout call is on a collection of nodes with no edges?

**Comment by aindlq** [comment]
Because user wants to be able to move around collapsed node. In your example when node is expanded it will be moved back to the initial position, but we want to expand it in place.

**Comment by metincansiper** [comment]
@aindlq 
In SBGNViz we handled the movement of collapsed nodes case in the following way. Before collapsing a compound we save the position of it before the collapse operation. Then when it is being expanded we calculate the difference between its current position and the position just before it is collapsed. Finally, we apply the same movements to the restored nodes.

@maxkfranz 
I think that in cose-bilkent we are creating layout nodes for appling CoSE layout in top-down approach starting from the orphans. I think that because of the reason that the orphan nodes are not passed to the layout the layout nodes are not created for these nodes and this problem can be solved if we start from the nodes whose parent do not exist between the nodes passed to the layout, instead of starting from the orphans, returned by cy.orphans().

**Comment by maxkfranz** [comment]
@metincansiper That sounds right.   `node.parent().intersection( layoutNodes ).empty()` is a safer check

**Comment by metincansiper** [comment]
I have created a function returning the list of top most nodes in a list of nodes. Then I used this method where I was using nodes.oprhans() previously. The problem seems to be solved now.

**Comment by ugurdogrusoz** [comment]
@aindlq could you please confirm your problem is fixed and close this issue if so?

**Comment by maxkfranz** [comment]
@metincansiper @ugurdogrusoz  If this change fixes it, then it can be `gulp publish`ed as 1.3.1

**Comment by aindlq** [comment]
Hm, maybe I'm doing something wrong but the only change that I can observe is that compound node is fit to viewport.

see http://jsbin.com/qimecaxose/edit?html,output


@metincansiper  Thank you for the suggestion, I really like the way you're doing it. This way layout of nodes inside compound after expand will be the same as before +1

**Comment by metincansiper** [comment]
@aindlq Thanks for noticing the bug. I made some corrections and it seems to be working now. I have also tried your fiddle and see that upon expand operation layout is being performed now. However, compound node still fits to viewport in your fiddle if you do not want this, you can specify the fit option of the layout as false. Could you please confirm that your problem is fixed. If it is fixed we can publish 1.3.1.

**Comment by aindlq** [comment]
@metincansiper thank you! works fine.

**Comment by metincansiper** [comment]
@aindlq we realized that while I was fixing this bug I made a logical mistake and something went wrong in version 1.3.1. Then I corrected that mistake and published version 1.3.2. We wanted to inform you about this. You may want to upgrade to cose-bilkent version 1.3.2.
