### ISSUE TITLE
Compond Title inside before click

### ISSUE THREAD

**Issue by fbacker** [cytoscape/cytoscape.js-cose-bilkent#19]
Using 1.3.6

After initialization the titles for compound (group) is inside the rectangle. If I click on the bounding box the title is moved on top (preferred). Is there a way to trigger so that all titles gets positioned correctly?

Left group is clicked, right is how it looks initialized
![alt text](https://dl.dropboxusercontent.com/u/27479515/forums/cose-bilkent-titles.png "Example")

**Comment by fbacker** [comment]
Some info to add here. I initialize the cy view with empty elements. Then making a api call and batch add all my nodes and edges.

**Comment by ugurdogrusoz** [comment]
I am not sure I understand. In this example you have 2 compound nodes, the top one has a label on top (which is desired), and the bottom one has a label not on top (inside the compound towards the top)? And when you click on the node, the label gets placed on top properly?

**Comment by metincansiper** [comment]
@maxkfranz I think that this problem emerges when the layout is used with the latest versions of Cytoscape.js and the animate option is 'end'. In the case of animate option is not 'during' we use 'layoutPositions' function (https://github.com/cytoscape/cytoscape.js-cose-bilkent/blob/master/src/Layout/index.js#L412). It works well if animate option is false, but it is problematic if it is 'end'. Also, in SBGNViz.js we are using Cytoscape.js version 2.6.12 and we are using 'animate: end' as default value, but we do not have such a problem there. Do you have an idea about this issue? I think that it may be something related to 'layoutPositions' or 'animate' function in the core.

**Comment by maxkfranz** [comment]
@metincansiper It just checks whether the value is truthy or not, so a string should be fine.  I don't think there's been any change to `.layoutPositions()` from 2.6 to 2.7

**Comment by metincansiper** [comment]
@maxkfranz Yes for sure a string should be fine because it is truthy and we do not have a problem with this because this if check is already successful and we have an animation when the animate option is 'end'. However, the problem described in this issue emerges if the animate option is 'end' though we are just using .layoutPositions() for this animation. I think that this problem may be related to .animate() or .animation() ( which seems to be internally called by .layoutPositions() )  too. If not what may be wrong with our usage of .layoutPositions() here (https://github.com/cytoscape/cytoscape.js-cose-bilkent/blob/master/src/Layout/index.js#L412).

**Comment by maxkfranz** [comment]
See 

- https://github.com/cytoscape/cytoscape.js/issues/1422 <= this suffices this particular case
- https://github.com/cytoscape/cytoscape.js/issues/1423 <= this fixes the more general case

**Comment by ugurdogrusoz** [comment]
Max's fixes at Cytoscape.js level fixes the problem.
