### ISSUE TITLE
Very Large Graph

### ISSUE THREAD

**Issue by JMOCARRO** [cytoscape/cytoscape.js-cose-bilkent#28]
Have you run this algorithm with very large networks (30K Nodes, 25K edges). If so what is the expected performance?

**Comment by ugurdogrusoz** [comment]
This is a cubic (in number of nodes) algorithm with potential to be improved to be quadratic (there is already  a related issue on this). On any case, I recommend complexity management (hide-show and expand-collapse, etc) support on such large graphs since finding your way around and doing effective analysis is not relasitic on such graphs.
