### ISSUE TITLE
Layout animation bug

### ISSUE THREAD

**Issue by ugurdogrusoz** [cytoscape/cytoscape.js-cose-bilkent#47]
This was discovered by @hasanbalci:
Open up daily Newt, set animation true (perform animation *during* layout), set incremental off (randomize: true) and perform layout on default graph. You'll see that at the very end of layout things get messed up (compounds placed in weird locations):
![neuronal_muscle_signalling 7](https://user-images.githubusercontent.com/3874988/27993160-809748aa-64ac-11e7-8dde-ccee0a825753.png)
This doesn't happen when animation if off (animation is set to 'end'). I don't know if this is somehow related to https://github.com/cytoscape/cytoscape.js-cose-bilkent/issues/45.
We suspect this was introduced after tiling was moved in l-level.

**Comment by metincansiper** [comment]
@ugurdogrusoz I made the requested change for #45 and it did not solve this problem as I expected (Because that change is inside ``` if(this.options.animate !== 'during')```, but in this case ```animate``` option is 'during'). 

Then, in cose-bilkent go back to  v1.6.7 where tiling is not moved to l-level yet. I see that this problem does not appear in v1.6.7. It appeared right after tiling is moved to l-level as you suspected.

**Comment by metincansiper** [comment]
@ugurdogrusoz it seems to be fixed now.

**Comment by ugurdogrusoz** [comment]
@hasanbalci can you verify and close the issue please?
