### ISSUE TITLE
Layout Problems in 1.0.4

### ISSUE THREAD

**Issue by timconnell** [cytoscape/cytoscape.js-cose-bilkent#8]
Version 1.0.2 works great for my project, but does not work in IE.  Version 1.0.4 works in IE, but lays out the nodes in a way that can't be right (tight diagonal line across the canvas).  This happens in both IE and Chrome. I've created a JSFiddle here using CDN code: [https://jsfiddle.net/pr8f5dLk/](https://jsfiddle.net/pr8f5dLk/).  Swap version numbers in the script tag to see the difference.

**Comment by metincansiper** [comment]
@timconnell 
The default randomize option was false in cose-bilkent but it was supposed to be true. Before, version 1.0.4 randomize option was not read properly because of an error and it was working as you expected by chance. In 1.0.4 and later versions it is read properly and as it is false, you get this result. In version 1.1.1 I have set the default randomize parameter as true and it seems that it is working as how you expected now. Note that randomize is a user option you can still set it as false. Also, I have noticed that in your example some of the edge sources/targets are not existing and these edges can not be created. You can see the javascript console logs in this example.

**Comment by timconnell** [comment]
Great!  Thanks for the help.  I know about the edges.  Unfortunately I'm working with live data that is not very clean.  This data came from a proof-of-concept based on real data.  In the final version we'll have a bit more control over missing nodes.  Do the missing nodes have a significant impact on the layout?
