### ISSUE TITLE
Setting nodeDimensionsIncludeLabels to true works not well for zero degree nodes

### ISSUE THREAD

**Issue by Does666** [cytoscape/cytoscape.js-cose-bilkent#88]
I set nodeDimensionsIncludeLabels to true to avoid label overlap, which is helpful. But for zero degree nodes , their layout looks out of order. Not N*M layout regularly.
 
I think the reason is that measure zero degree nodes position should use the width of node, which also include the width of label. But the width of label is not fixed depend on the text.

**Comment by Does666** [comment]
So is it possible to set label width or set boundingbox of node ?

**Comment by ugurdogrusoz** [comment]
@Does666 I am not sure I understand your concern. If node labels are considered in node dimensions and node labels do not have uniform dimensions, you should expect a grid layout for disconnected nodes when they are tiled.
Why not truncate your labels above a certain width to ensure uniformity if it's important for you?

**Comment by Does666** [comment]
@ugurdogrusoz Thanks for your reply. I think you got my concern.
I use `cose-bilkent` layout and `cytoscape.js-expand-collapse` extension for the `compound` feature. The disconnected nodes exists on diffrent groups. 
1. Is it possible to layout nodes with edges with `cose-bilkent` and layout nodes disconnected with `grid` ?
2. Some label text maybe a letter, while some text maybe a long label.  I have set `text-max-width 120px`  for all nodes. But I can't truncate all labels a certain width. I expect the label only with a letter also has width 120px.

**Comment by ugurdogrusoz** [comment]
When *tile* is true, we tile/pack disconnected nodes w.r.t. their dimensions. In below example, since labels *are* considered, this is the tiling we get:
![image](https://user-images.githubusercontent.com/3874988/63938890-949c5f00-ca6e-11e9-87bb-2bb213c7b12e.png)
I suppose you'd like to see the actual nodes tiled to a grid. This is not something this layout style will do under any circumstances since it strives to minimize area.
Your other more general Cytsocape.js related questions, I suggest you ask them in proper forums.
