### ISSUE TITLE
v4.1.0 has breaking changes to v4.0

### ISSUE THREAD

**Issue by ohemsted-thales** [cytoscape/cytoscape.js-cose-bilkent#90]
It's also notable that the file size has reduced from 5536 lines to 458 lines. It appears that the layout fails to initialise under the new build.

```
cytoscape-cose-bilkent.js:92 Uncaught TypeError: Cannot read property 'layoutBase' of undefined
    at Object.<anonymous> (cytoscape-cose-bilkent.js:92)
    at __webpack_require__ (cytoscape-cose-bilkent.js:30)
    at cytoscape-cose-bilkent.js:76
    at cytoscape-cose-bilkent.js:79
    at webpackUniversalModuleDefinition (cytoscape-cose-bilkent.js:9)
    at cytoscape-cose-bilkent.js:10
```

**Comment by hasanbalci** [comment]
@ohemsted-thales We refactored the code and moved an important part of it to two different repositories ([cose-base](https://github.com/iVis-at-Bilkent/cose-base) and [layout-base](https://github.com/iVis-at-Bilkent/layout-base)) which are dependencies of the extension now. That's why the file size reduced. If your are using `npm install cytoscape-cose-bilkent ` then these dependencies should be installed automatically and you should be able to build or run the extension. 

If you're using it in plain HTML/JS like in the extension demo, then you need to include these dependencies manually:
```
    <script src="https://unpkg.com/layout-base/layout-base.js"></script>
    <script src="https://unpkg.com/cose-base/cose-base.js"></script>
    <script src="cytoscape-cose-bilkent.js"></script>
```

**Comment by ohemsted-thales** [comment]
Should this not have been mentioned in the release notes? According to the https://semver.org/ it should add functionality in a backwards compatible way.

> Given a version number MAJOR.MINOR.PATCH, increment the:
> MAJOR version when you make incompatible API changes,
> MINOR version when you add functionality in a backwards compatible manner, and
> PATCH version when you make backwards compatible bug fixes.

Thanks for your help, the steps listed above did resolve the issue we were facing.

**Comment by ugurdogrusoz** [comment]
@ohemsted-thales Thanks for pointing out this backward compatibility issue. We didn't actually make any changes in the API; that's why we went with a minor version increment. We'll make sure to document this more.

**Comment by ohemsted-thales** [comment]
Thanks again for the quick responses 👍
